config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end


  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :body
  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern
  def self.image_generator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}"
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image
  def self.angular
    where(subtitle: "Angular")
  end
  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }
  after_initialize :set_defaults
  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized
  after_initialize :set_defaults
  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :name
  def first_name
    self.name.split.first
  end
  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist
  before_action :set_source
  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.published?
      @blog.draft!
    elsif @blog.draft?
      @blog.published!
    end
    redirect_to blogs_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern
  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def create
    @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]))

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolio_show_url(@portfolio_item), notice: "Portfolio Item was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
        format.html { redirect_to portfolios_url, notice: "Portfolio Item was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Portfolio Item was successfully destroyed." }
    end
  end


  # private
    # Use callbacks to share common setup or constraints between actions.
    # def set_blog
    #   @blog = Blog.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    # def portfolio_item_params
    #   params.require(:portfolio).permit(:title, :subtitle, :body)
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog.body %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <div id="<%= dom_id blog %>">
      <p>
        <strong>Title:</strong>
        <%= link_to blog.title, blog %>
      </p>

      <p>
        <strong>Body:</strong>
        <%= blog.body %>
      </p>

      <%= link_to blog.status, toggle_status_blog_path(blog) %>

    </div>
  <% end %>
</div>

<%= link_to "New blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
    <%= yield %>
    <p>Thanks for visiting from <%= session[:source] %></p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name if current_user%></h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog Post</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item) do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div id="<%= dom_id portfolio %>">
  
  <%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>

  <p>
    <strong>Title:</strong>
    <%= portfolio.title %>
  </p>
  <p>
    <strong>Subtitle:</strong>
    <%= portfolio.subtitle %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= portfolio.body %>
  </p>

  <h2>Technologies Used:</h2>
  <% portfolio.technologies.each do |t| %>
    <p><%= t.name %></p>
  <% end %>

</div>

<%= params.inspect %>
<hr>

<%= session.inspect %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
  <%= button_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio Item</h1>

<%= form_with(model: @portfolio_item) do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<br>

<div>
  <%= link_to "Back", portfolios_path %>
</div>

app/views/portfolios/index.html.erb
<h1>Portfolio items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<% @portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
  <%= button_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= form_with(model: @portfolio_item) do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<br>

app/views/portfolios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @portfolio_item %>

<div>
  <%= link_to "Edit", edit_portfolio_path(@portfolio_item) %> |
  <%= link_to "Back", portfolios_path %>

  <%= button_to "Delete Portfolio Item", portfolio_path(@portfolio_item), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %>
</div>